name: Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'  # Change to your .NET version

    - name: Install required .NET workloads
      run: dotnet workload restore

    - name: Clean solution
      run: dotnet clean

    - name: Build solution
      run: dotnet build --configuration Release

    - name: List build outputs
      run: dir bin\Debug\net6.0  # Adjust if targeting a different framework

    - name: Run tests
      run: dotnet test --no-build --verbosity detailed --logger "trx;LogFileName=test_results.trx"
