name: Run Selenium C# Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu, windows, macos ]  # Run tests on multiple OSes
    runs-on: ${{ matrix.os }}-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up .NET environment
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.x'  # Specify your .NET version

    # Optional: For Ubuntu - Start virtual framebuffer for GUI-based tests
    - name: Start Xvfb for Ubuntu
      if: matrix.os == 'ubuntu'
      run: Xvfb :99 &

    - name: Restore NuGet packages
      run: dotnet restore SeleniumTestCsharp.sln

    - name: Build the project
      run: dotnet build --configuration Release

    - name: Run Selenium tests
      run: dotnet test --no-build --verbosity normal --logger "trx;LogFileName=test_results.trx"

    # Optional: Upload test results to GitHub Actions
    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: Test Results
        path: test_results.trx
