name: Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'  # Adjust to your .NET version

    - name: Restore NuGet packages
      run: dotnet restore SeleniumTestCsharp.sln

    - name: Build solution
      run: dotnet build --configuration Release

    - name: List build outputs
      run: dir bin\Debug\net6.0  # Adjust if using another framework

    - name: Run tests
      run: dotnet test --no-build --verbosity detailed
